/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as PollsCreateRouteImport } from './routes/polls/create'
import { Route as PollsPollIdRouteImport } from './routes/polls/$pollId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsCreateRoute = PollsCreateRouteImport.update({
  id: '/polls/create',
  path: '/polls/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsPollIdRoute = PollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/polls/create': typeof PollsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/polls/create': typeof PollsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/polls/create': typeof PollsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/following'
    | '/login'
    | '/register'
    | '/polls/$pollId'
    | '/polls/create'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/following'
    | '/login'
    | '/register'
    | '/polls/$pollId'
    | '/polls/create'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/following'
    | '/login'
    | '/register'
    | '/polls/$pollId'
    | '/polls/create'
    | '/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PollsPollIdRoute: typeof PollsPollIdRoute
  PollsCreateRoute: typeof PollsCreateRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/create': {
      id: '/polls/create'
      path: '/polls/create'
      fullPath: '/polls/create'
      preLoaderRoute: typeof PollsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$pollId': {
      id: '/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof PollsPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PollsPollIdRoute: PollsPollIdRoute,
  PollsCreateRoute: PollsCreateRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
